version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: properties_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: app
    depends_on:
      - mysql-db
    ports:
      - "35000:35000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/properties_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
